{% set xorg_name = "libXp" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.0.4" %}
{% set am_version = "1.16" %} # keep synchronized with build.sh

# Note that this library is deprecated by X.org and will may not ever see
# another release.

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: 1f19e3b8e82a34a8fd9889a7d9af0abe8588cb03fb57c37c569634cf3b9df1a4

build:
  number: 0
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - m2-autoconf                  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool                   # [win]
    - pkg-config                   # [unix]
    - m2-pkg-config                # [win]
    - gnuconfig                    # [unix]
    - m2-base                      # [win]
    - make                         # [unix]
    - m2-make                      # [win]
    - {{ compiler("c") }}          # [unix]
    - {{ stdlib("c") }}            # [unix]
    - {{ compiler("m2w64_c") }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
  host:
    - pthread-stubs
    - xorg-xorgproto
    - xorg-printproto  # this is deprecated and *not* rolled up into xorgproto
    - xorg-util-macros
    - xorg-libx11
    - xorg-libxau
    - xorg-libxext

test:
  commands:
    {% set lib_idents = [ "Xp" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ lib_ident }}.so  # [linux]
    - if not exist %PREFIX%/Library/lib/lib{{ lib_ident }}.dll.a exit /b 1  # [win]
    - if not exist %PREFIX%/Library/bin/msys-{{ lib_ident }}-*.dll exit /b 1  # [win]
    {% endfor %}

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'The X.org print library.'

extra:
  recipe-maintainers:
    - pkgw
    - epruesse
