{% set xorg_name = "libXp" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.0.3" %}
{% set sha256 = "7f360c9905849c3587d48efc0f0ecbc852c19f61a52b18530d6b005cb9148c57" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 1
  detect_binary_files_with_prefix: true

  # Windows build failing. See https://ci.appveyor.com/project/epruesse/staged-recipes/build/1.0.64/job/p3bt0xipb8cms0hm#L1194
  # Error:
  # In file included from XpJob.c:44:0:
  # $PREFIX/include/X11/extensions/Printstr.h:116:18: error: conflicting types for 'CARD32'
  # #define PCONTEXT CARD32
  #                ^
  # In file included from $PREFIX/include/X11/Xproto.h:72:0,
  #               from $PREFIX/include/X11/extensions/Printstr.h:64,
  #               from XpJob.c:44:
  # $PREFIX/include/X11/Xmd.h:111:23: note: previous declaration of 'CARD32' was here
  # typedef unsigned long CARD32;
  skip: True  # [win]

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - m2w64-pkg-config  # [win]
    - pkg-config  # [not win]
    - posix  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - pthread-stubs
    - xorg-xextproto
    - xorg-printproto
    - xorg-util-macros  # [win]
    - xorg-libx11 1.6.*
    - xorg-libxau
    - xorg-libxext
  run:
    - xorg-libx11 1.6.*
    - xorg-libxau
    - xorg-libxext

test:
  commands:
    {% set lib_idents = [ "Xp" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ lib_ident }}.so  # [linux]
    - if not exist %PREFIX%/Library/lib/lib{{ lib_ident }}.dll.a exit /b 1  # [win]
    - if not exist %PREFIX%/Library/lib/lib{{ lib_ident }}.a exit /b 1  # [win]
    - if not exist %PREFIX%/Library/lib/lib{{ lib_ident }}.la exit /b 1  # [win]
    - if not exist %PREFIX%/Library/bin/msys-{{ lib_ident }}-*.dll exit /b 1  # [win]
    {% endfor %}
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'The X.org print library.'

extra:
  recipe-maintainers:
    - pkgw
    - epruesse
