travis:
  secure:
    BINSTAR_TOKEN: SXCg2WWD/ntKvoI87IDX3mmv/V4WEr9EfpsDnrtKPTNHxadPSDzY6RCpeTzxzTQXB+jgwnRZ9XnAJoGBt/UGojLl5ugP+aGk0nGLkwa9SHkPrn4nnY8zwbz1xu2x6apqAVuIeR4IudAlTxVv0U04ZyoP+Kspe1fWgXRpiNBFLzHDfd24MWSpVVcGFDTrqsIycVV/B6xKe2F4x084zpXO45VHD2WdocaZCF2k6iIVA9LCwKlc4UkJMpJIurZxqCBXuyJq133qIY+DgPywLBXn6pSpb2RYSMq7HfuK3Vlb1rcrH1fCo3R6oq4fjsRwaM7K8Sz76D3h0dcW7uaZWAuGw+8PrJAjWeWrpwuWcF2GX8MCFL2GpXLbE2ujHIhTNVo3SZ8tKC8qxZ0e85YDpW9pfoR6w5X91gtVz4Z30vh6kLAtrN+wepD9bPgCHmG8YdNKPR2FXWznOkccW0Uzv7/5myK8f87ROCLIQQImO8S5xRH4OUa52eeXiiowG6lmuOSJbHbr3wbh5AzzloMih/5fVrrFqKxOweJPcuMW2NYIWo0ykw80iVmLHKIYIuP+nw5WT0Q9uxDqDuEXQ0JsdU4YDfqrkOF0kDURVMqBvHfy+iVZeY7PGZk4zHtJDX26h75CN0l56wWgtphVdUv29np9W9OOWvfm92BZFsVzTPIvizQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
