travis:
  secure:
    BINSTAR_TOKEN: Lax3qhmkomW7ReKGhUbuMTBd3e5ewQj/GYOVouy3qYyuuVgs9s7VTp4nsRWao3NkzJlD33dqPu06LmSc03wjCm4CrqeheZnVIC4oysDNRaTRF7YhuAfgImXkWlNyWSBTPOkGz/cbt4XlusrjK22JCRAgtiRLN8plFVFhrKUF+urY967rvt/rd0Cx6XsuCZnDUFiwFaziqaCj4r+x9k1vEfHNsgEiwolnQUWGFRY6mbOFUxkuR9yyiHaFmJazD0ekuQCSnOraElqNYYJUrqtcAKGohL6q+aZshDFeWaGHvA3npe7goxqOsKE2W5/lyFxzBUNOoycfrlcnqFoXVOSb1TMUXWc7+1N4+Xdv3Hnnvzm3zSTvat9U4+fJQH3Z9fdinPrvx9ToybvI2/JtnHyKOLYTsmBeM3+zTEgHJ1gKuJz5LHO40mhVfivm40X9fTlmaUOfKU9+RDgdHAc3ftbYwbecYdT8reKuRGvdg/VZThMWAli2cFBWIgZ1vd5MParTqwlC6Z5Zmbsprf6sOPIN94+u+KQGjGnGPgSz5pmyWEL1mMv1oJK/TT2DhCQ/q7ZJibkMeLqf5DsBXTNVtL74ogRld/qjj0u1A4hKwjHwytAbSAfLA7PVp/O52UiLavtssGeZWa5ruVjjkcZOXaWQErruOSRWZOigvMsj82ahJ7g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
